### ISSUE TITLE
some question with AndroidStreamingClient

### ISSUE THREAD

**Issue by ZhuChaozheng** [ekumenlabs/AndroidStreamingClient#56]
when I want to try the example project,there are some errors in Eclipse,
like

```E/AndroidRuntime(25286): java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.c77.androidstreamingclient.example/com.c77.androidstreamingclient.example.DecoderMainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.c77.androidstreamingclient.example.DecoderMainActivity" on path: DexPathList[[zip file "/data/app/com.c77.androidstreamingclient.example-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.c77.androidstreamingclient.example-2, /vendor/lib, /system/lib]],```

**Comment by adamantivm** [comment]
@ZhuChaozheng this sounds like a problem with the project set-up in Eclipse, particularly the classpath.
Can you provide more detail on how you set-up the example project in Eclipse until you got to that error?

Also take into account that the example project is prapared for Android Studio, not for Eclipse, so you will have to do some kind of import process to make it work on Eclipse, we haven't tried that yet.

**Comment by ZhuChaozheng** [comment]
OK,I will hava a try with Android Studio.Thank you!

**Comment by adamantivm** [comment]
This issue seems to have been addressed.
